image: ksimple/java8-mvn-nodejs-npm-python3
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - init: mvn package
    command: java -jar target/drawingboard-light-1.0-SNAPSHOT-jar-with-dependencies.jar